run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - godot
    - goprintffuncname
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - filepathJoin
      - unnamedResult
      - singleCaseSwitch
      - stringXbytes
  gosec:
    excludes:
      - G306  # Expect WriteFile permissions to be 0600 or less (false positive for test files)
      - G107  # Potential HTTP request made with variable url (false positive for our use case)
      - G204  # Subprocess launched with a potential tainted input (false positive for our use case)
  godot:
    scope: declarations
    period: true
    capital: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - gosec
        - goconst
    - path: integration_test\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
        - gosec
        - goconst
    - path: cmd/
      linters:
        - gocyclo
    - path: internal/
      linters:
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0 