name: BlueBanquise Installer CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  # Unit tests and linting
  test:
    name: Unit Tests & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m --out-format=colored-line-number

      - name: Build binary
        run: go build -o bluebanquise-installer .

  # Online installation tests
  test-online-installation:
    name: Online Installation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build installer
        run: go build -o bluebanquise-installer .

      - name: Test online installation on Rocky Linux 9
        run: |
          # Create Rocky Linux 9 container as root
          docker run -d --name test-online-rocky9 \
            --privileged \
            --user root \
            -v $(pwd):/installer \
            rockylinux:9 \
            tail -f /dev/null
          
          # Wait for container to be ready
          sleep 10
          
          # Install Python 3.12 and dependencies
          docker exec test-online-rocky9 bash -c "
            dnf install -y python3.12 python3.12-pip python3.12-devel git curl python3.12-setuptools --allowerasing
            ln -sf /usr/bin/python3.12 /usr/bin/python3
            ln -sf /usr/bin/pip3.12 /usr/bin/pip3
          "
          
          # Wait for dependencies to be fully installed
          sleep 5
          
          # Run online installation (as root in container)
          docker exec test-online-rocky9 bash -c "
            cd /installer
            ./bluebanquise-installer online --user testuser --home /tmp/bluebanquise
          "
          
          # Wait for installation to complete and any background processes
          sleep 10
                    
          # Cleanup
          docker stop test-online-rocky9
          docker rm test-online-rocky9

  # Offline installation tests
  test-offline-installation:
    name: Offline Installation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build installer
        run: go build -o bluebanquise-installer .

      - name: Test offline installation on Rocky Linux 9
        run: |
          # Create Rocky Linux 9 container as root
          docker run -d --name test-offline-rocky9 \
            --privileged \
            --user root \
            -v $(pwd):/installer \
            rockylinux:9 \
            tail -f /dev/null
          
          # Wait for container to be ready
          sleep 10
          
          # Install Python 3.12 and dependencies
          docker exec test-offline-rocky9 bash -c "
            dnf install -y python3.12 python3.12-pip python3.12-devel git curl python3.12-setuptools --allowerasing
            ln -sf /usr/bin/python3.12 /usr/bin/python3
            ln -sf /usr/bin/pip3.12 /usr/bin/pip3
          "
          
          # Wait for dependencies to be fully installed
          sleep 5
          
          # Download collections for offline test
          docker exec test-offline-rocky9 bash -c "
            cd /installer
            mkdir -p /tmp/offline-packages
            ./bluebanquise-installer download --path /tmp/offline-packages/collections
            ./bluebanquise-installer download --path /tmp/offline-packages/requirements --requirements
          "
          
          # Wait for downloads to complete
          sleep 5
          
          # Run offline installation (as root in container)
          docker exec test-offline-rocky9 bash -c "
            cd /installer
            ./bluebanquise-installer offline --collections-path /tmp/offline-packages/collections --requirements-path /tmp/offline-packages/requirements --user testuser --home /tmp/bluebanquise
          "
          
          # Wait for installation to complete and any background processes
          sleep 10
                    
          # Cleanup
          docker stop test-offline-rocky9
          docker rm test-offline-rocky9

  # Tarball installation tests
  test-tarball-installation:
    name: Tarball Installation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build installer
        run: go build -o bluebanquise-installer .

      - name: Test tarball installation on Rocky Linux 9
        run: |
          # Create Rocky Linux 9 container as root
          docker run -d --name test-tarball \
            --privileged \
            --user root \
            -v $(pwd):/installer \
            rockylinux:9 \
            tail -f /dev/null
          
          # Wait for container to be ready
          sleep 10
          
          # Install Python 3.12 and dependencies
          docker exec test-tarball bash -c "
            dnf install -y python3.12 python3.12-pip python3.12-devel git curl python3.12-setuptools --allowerasing
            ln -sf /usr/bin/python3.12 /usr/bin/python3
            ln -sf /usr/bin/pip3.12 /usr/bin/pip3
          "
          
          # Wait for dependencies to be fully installed
          sleep 5
          
          # Download tarballs for offline test
          docker exec test-tarball bash -c "
            cd /installer
            mkdir -p /tmp/tarball-packages
            ./bluebanquise-installer download --path /tmp/tarball-packages --tarball
            ./bluebanquise-installer download --path /tmp/tarball-packages/requirements --requirements
          "
          
          # Wait for downloads to complete
          sleep 5
          
          # Run offline installation with tarballs (as root in container)
          docker exec test-tarball bash -c "
            cd /installer
            ./bluebanquise-installer offline --tarball-path /tmp/tarball-packages --requirements-path /tmp/tarball-packages/requirements --user testuser --home /tmp/bluebanquise
          "
          
          # Wait for installation to complete and any background processes
          sleep 10
                    
          # Cleanup
          docker stop test-tarball
          docker rm test-tarball

  # Different architectures tests
  test-architectures:
    name: Architecture Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build for ${{ matrix.arch }}
        run: |
          GOOS=linux GOARCH=${{ matrix.arch }} go build -o bluebanquise-installer-${{ matrix.arch }} .

      - name: Test binary on ${{ matrix.arch }}
        run: |
          # Test binary directly (no container needed for architecture test)
          chmod +x bluebanquise-installer-${{ matrix.arch }}
          export LOG_DIR=/tmp/log && mkdir -p $LOG_DIR
          LOG_DIR=$LOG_DIR ./bluebanquise-installer-${{ matrix.arch }} --help

  # Complete integration tests
  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build installer
        run: go build -o bluebanquise-installer .

      - name: Run integration tests
        run: |
          # Run integration tests
          go test -v -tags=integration ./...
          
          # Test basic commands
          ./bluebanquise-installer --help
          ./bluebanquise-installer status --help
          ./bluebanquise-installer online --help
          ./bluebanquise-installer offline --help
          ./bluebanquise-installer download --help

  # Build and release
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    needs: [test, test-online-installation, test-offline-installation, test-tarball-installation, test-architectures, test-integration]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o bluebanquise-installer-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o bluebanquise-installer-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o bluebanquise-installer-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o bluebanquise-installer-darwin-arm64 .

      - name: Create release assets
        run: |
          mkdir -p release
          cp bluebanquise-installer-* release/
          cp README.md release/
          cp LICENSE release/ 2>/dev/null || echo "No LICENSE file found"

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: bluebanquise-installer-release
          path: release/ 